// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF6Vtc_l1iIBSv3bVknUgR9Uctp_gRoVQ',
    appId: '1:595049478902:web:ac9cd1f0a449569400cad7',
    messagingSenderId: '595049478902',
    projectId: 'ivory-hallway-376807',
    authDomain: 'ivory-hallway-376807.firebaseapp.com',
    storageBucket: 'ivory-hallway-376807.appspot.com',
    measurementId: 'G-PTDY68PFKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE13y8E9LcxlERLUnW1LVML0JhkQ_6DTg',
    appId: '1:595049478902:android:779105cb258317fd00cad7',
    messagingSenderId: '595049478902',
    projectId: 'ivory-hallway-376807',
    storageBucket: 'ivory-hallway-376807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADwniIP_KjmOCC8gTjrNnHM62xh_BCvn8',
    appId: '1:595049478902:ios:714b356a264641a900cad7',
    messagingSenderId: '595049478902',
    projectId: 'ivory-hallway-376807',
    storageBucket: 'ivory-hallway-376807.appspot.com',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADwniIP_KjmOCC8gTjrNnHM62xh_BCvn8',
    appId: '1:595049478902:ios:2eb77c4a88d61f2a00cad7',
    messagingSenderId: '595049478902',
    projectId: 'ivory-hallway-376807',
    storageBucket: 'ivory-hallway-376807.appspot.com',
    iosBundleId: 'com.example.message.RunnerTests',
  );
}
